version: '3.8'

services:
  db:
    container_name: "postgresUsers"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=usuarios
    ports:
      - '5432:5432'
