version: '3.1'
services:
  mariadb:
    container_name: "ProductosMariadb"
    image: mariadb:latest
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mariadbpass"
      MYSQL_DATABASE: "productosTest"
      MYSQL_USER: "mariadbadmin"
      MYSQL_PASSWORD: "mariadbpass"